// <auto-generated />
using System;
using BussinessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BussinessObject.Migrations
{
    [DbContext(typeof(PawnShopContext))]
    [Migration("20241103143104_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BussinessObject.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<DateTime>("DateBuy")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BillId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            BillId = 1,
                            DateBuy = new DateTime(2024, 10, 24, 21, 31, 4, 40, DateTimeKind.Local).AddTicks(6866),
                            ShopItemId = 1,
                            UserId = 1
                        },
                        new
                        {
                            BillId = 2,
                            DateBuy = new DateTime(2024, 10, 29, 21, 31, 4, 40, DateTimeKind.Local).AddTicks(6872),
                            ShopItemId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BussinessObject.CapitalInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("TotalCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExpenditure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CapitalInformation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TotalCapital = 1000.00m,
                            TotalExpenditure = 300.00m,
                            TotalIncome = 500.00m
                        });
                });

            modelBuilder.Entity("BussinessObject.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Description = "14K Gold Ring",
                            ExpirationDate = new DateTime(2024, 12, 3, 21, 31, 4, 40, DateTimeKind.Local).AddTicks(6592),
                            Interest = 0.05m,
                            IsApproved = true,
                            Name = "Gold Ring",
                            Status = "Pending",
                            UserId = 1,
                            Value = 250.00m
                        },
                        new
                        {
                            ItemId = 2,
                            Description = "Luxury Watch",
                            ExpirationDate = new DateTime(2025, 1, 3, 21, 31, 4, 40, DateTimeKind.Local).AddTicks(6616),
                            Interest = 0.10m,
                            IsApproved = true,
                            Name = "Luxury Watch",
                            Status = "Active",
                            UserId = 2,
                            Value = 500.00m
                        });
                });

            modelBuilder.Entity("BussinessObject.PawnContract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ContractId");

                    b.ToTable("PawnContracts");

                    b.HasData(
                        new
                        {
                            ContractId = 1,
                            ContractDate = new DateTime(2024, 11, 3, 21, 31, 4, 40, DateTimeKind.Local).AddTicks(6794),
                            ExpirationDate = new DateTime(2024, 12, 3, 21, 31, 4, 40, DateTimeKind.Local).AddTicks(6795),
                            ItemId = 1,
                            LoanAmount = 200.00m,
                            UserId = 1
                        },
                        new
                        {
                            ContractId = 2,
                            ContractDate = new DateTime(2024, 11, 3, 21, 31, 4, 40, DateTimeKind.Local).AddTicks(6797),
                            ExpirationDate = new DateTime(2025, 1, 3, 21, 31, 4, 40, DateTimeKind.Local).AddTicks(6797),
                            ItemId = 2,
                            LoanAmount = 400.00m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BussinessObject.ShopInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ShopAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShopInformation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ShopAddress = "FPT University",
                            ShopName = "FPT Pawn Shop",
                            Telephone = "1234-5555"
                        });
                });

            modelBuilder.Entity("BussinessObject.ShopItem", b =>
                {
                    b.Property<int>("ShopItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopItemId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ShopItemId");

                    b.ToTable("ShopItemn");

                    b.HasData(
                        new
                        {
                            ShopItemId = 1,
                            DateAdded = new DateTime(2024, 11, 3, 21, 31, 4, 40, DateTimeKind.Local).AddTicks(6759),
                            Description = "High performance laptop for gaming.",
                            IsExpired = false,
                            Name = "Gaming Laptop",
                            Price = 750.00m
                        },
                        new
                        {
                            ShopItemId = 2,
                            DateAdded = new DateTime(2024, 11, 3, 21, 31, 4, 40, DateTimeKind.Local).AddTicks(6761),
                            Description = "Latest smartphone with advanced features.",
                            IsExpired = false,
                            Name = "Latest Model Smartphone",
                            Price = 300.00m
                        });
                });

            modelBuilder.Entity("BussinessObject.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserRealName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Address = "123 Main St",
                            CID = "C123456789",
                            Dob = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "john.doe@example.com",
                            Gender = true,
                            Password = "Password123",
                            Telephone = "123-456-7890",
                            UserName = "john_doe",
                            UserRealName = "John Doe",
                            UserRole = 1
                        },
                        new
                        {
                            UserID = 2,
                            Address = "456 Oak St",
                            CID = "C987654321",
                            Dob = new DateTime(1988, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jane.smith@example.com",
                            Gender = false,
                            Password = "Password456",
                            Telephone = "098-765-4321",
                            UserName = "jane_smith",
                            UserRealName = "Jane Smith",
                            UserRole = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
