// <auto-generated />
using System;
using BussinessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BussinessObject.Migrations
{
    [DbContext(typeof(PawnShopContext))]
    partial class PawnShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BussinessObject.CapitalInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("TotalCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExpenditure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CapitalInformation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TotalCapital = 0m,
                            TotalExpenditure = 0m,
                            TotalIncome = 0m
                        });
                });

            modelBuilder.Entity("BussinessObject.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Description = "14K Gold Ring",
                            ExpirationDate = new DateTime(2024, 12, 3, 17, 9, 56, 597, DateTimeKind.Local).AddTicks(7867),
                            Interest = 0.05m,
                            IsApproved = true,
                            Name = "Gold Ring",
                            Status = "Pending",
                            Value = 250.00m
                        },
                        new
                        {
                            ItemId = 2,
                            Description = "Luxury Watch",
                            ExpirationDate = new DateTime(2025, 1, 3, 17, 9, 56, 597, DateTimeKind.Local).AddTicks(7889),
                            Interest = 0.10m,
                            IsApproved = true,
                            Name = "Watch",
                            Status = "Active",
                            Value = 500.00m
                        });
                });

            modelBuilder.Entity("BussinessObject.PawnContract", b =>
                {
                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ContractId", "ItemId");

                    b.ToTable("PawnContracts");

                    b.HasData(
                        new
                        {
                            ContractId = 1,
                            ItemId = 1,
                            ContractDate = new DateTime(2024, 11, 3, 17, 9, 56, 597, DateTimeKind.Local).AddTicks(8041),
                            ExpirationDate = new DateTime(2024, 12, 3, 17, 9, 56, 597, DateTimeKind.Local).AddTicks(8041),
                            LoanAmount = 200.00m,
                            UserId = 1
                        },
                        new
                        {
                            ContractId = 2,
                            ItemId = 2,
                            ContractDate = new DateTime(2024, 11, 3, 17, 9, 56, 597, DateTimeKind.Local).AddTicks(8043),
                            ExpirationDate = new DateTime(2025, 1, 3, 17, 9, 56, 597, DateTimeKind.Local).AddTicks(8044),
                            LoanAmount = 400.00m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BussinessObject.ShopInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ShopAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShopInformation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ShopAddress = "FPT University",
                            ShopName = "FPT Pawn Shop",
                            Telephone = "1234-5555"
                        });
                });

            modelBuilder.Entity("BussinessObject.ShopItem", b =>
                {
                    b.Property<int>("ShopItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopItemId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ShopItemId");

                    b.ToTable("ShopItemn");

                    b.HasData(
                        new
                        {
                            ShopItemId = 1,
                            DateAdded = new DateTime(2024, 11, 3, 17, 9, 56, 597, DateTimeKind.Local).AddTicks(8013),
                            Description = "Gaming Laptop",
                            IsExpired = false,
                            Name = "Laptop",
                            Price = 750.00m
                        },
                        new
                        {
                            ShopItemId = 2,
                            DateAdded = new DateTime(2024, 11, 3, 17, 9, 56, 597, DateTimeKind.Local).AddTicks(8015),
                            Description = "Latest Model Smartphone",
                            IsExpired = false,
                            Name = "Smartphone",
                            Price = 300.00m
                        });
                });

            modelBuilder.Entity("BussinessObject.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserRealName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
